names:
- PET
- LDPE
- Raffia
- HDPE
- PVC
- PP
- MLP
- thermacol
- Rubber
- Tyre
- Paper
- Cardboard
- Metal
- E-waste
- Glass
- Textile
nc: 16
test: dataset/images/test
train: dataset/images/train
val: dataset/images/val
